export const hoursData = [
    { hour: 'Cerrado' },
    { hour: '12AM' },
    { hour: '12:30AM' },
    { hour: '1AM' },
    { hour: '1:30AM' },
    { hour: '2AM' },
    { hour: '2:30AM' },
    { hour: '3AM' },
    { hour: '3:30AM' },
    { hour: '4AM' },
    { hour: '4:30AM' },
    { hour: '5AM' },
    { hour: '5:30AM' },
    { hour: '6AM' },
    { hour: '6:30AM' },
    { hour: '7AM' },
    { hour: '7:30AM' },
    { hour: '8AM' },
    { hour: '8:30AM' },
    { hour: '9AM' },
    { hour: '9:30AM' },
    { hour: '10AM' },
    { hour: '10:30AM' },
    { hour: '11AM' },
    { hour: '11:30AM' },
    { hour: '12PM' },
    { hour: '12:30PM' },
    { hour: '1PM' },
    { hour: '1:30PM' },
    { hour: '2PM' },
    { hour: '2:30PM' },
    { hour: '3PM' },
    { hour: '3:30PM' },
    { hour: '4PM' },
    { hour: '4:30PM' },
    { hour: '5PM' },
    { hour: '5:30PM' },
    { hour: '6PM' },
    { hour: '6:30PM' },
    { hour: '7PM' },
    { hour: '7:30PM' },
    { hour: '8PM' },
    { hour: '8:30PM' },
    { hour: '9PM' },
    { hour: '9:30PM' },
    { hour: '10PM' },
    { hour: '10:30PM' },
    { hour: '11PM' },
    { hour: '11:30PM' }
];

export const categories = [
    { category: 'Parque de diversiones' },
    { category: 'Tienda para bebés' },
    { category: 'Banco' },
    { category: 'Bar' },
    { category: 'Cafetería' },
    { category: 'Carpintería' },
    { category: 'Iglesia' },
    { category: 'Ropa' },
    { category: 'Cocteles' },
    { category: 'Fábrica' },
    { category: 'Ropa femenina' },
    { category: 'Fotografía' },
    { category: 'Jardinería' },
    { category: 'Gasolinera' },
    { category: 'Piñatería' },
    { category: 'Marroquinería' },
    { category: 'Heladería' },
    { category: 'Ferretería' },
    { category: 'Joyería' },
    { category: 'Comida Rápida' },
    { category: 'Librería' },
    { category: 'Financiamiento' },
    { category: 'Logística' },
    { category: 'Centro comercial' },
    { category: 'Mercado' },
    { category: 'Películas' },
    { category: 'Música' },
    { category: 'Odontología' },
    { category: 'Oficina' },
    { category: 'Mascotas' },
    { category: 'Farmacia' },
    { category: 'Pizzería' },
    { category: 'Ropa de alquiler' },
    { category: 'Restaurante' },
    { category: 'Sex shop' },
    { category: 'Zapatería' },
    { category: 'Tecnología' },
    { category: 'Timer' },
    { category: 'Veterinaria' },
    { category: 'Videojuegos' },
    { category: 'Otro' }
];

export const scheduleData = [
    { days: 'Lunes a Viernes' },
    { days: 'Lunes a Domingo' },
    { days: 'Personalizado' }
];

export const headers: string[] = ['Día', 'Abre', 'Cierra'];

export const colors: string[] = [
    '#F1C40F',
    '#FF5733',
    '#00A86B',
    '#6A2CCD',
    '#D1CA2F',
    '#F39C12',
    '#3498DB',
    '#E74C3C',
    '#2ECC71',
    '#9B59B6',
    '#1ABC9C',
    '#E67E22',
    '#2980B9',
    '#C0392B',
    '#27AE60',
    '#8E44AD',
    '#8899CB',
    '#2C3E50',
    '#16A085',
    '#8E44AD',
    '#F1C40F',
    '#3498DB',
    '#FF000A',
    '#00CF0B',
    '#1200FF',
    '#0223FF',
    '#0089EF',
    '#0450FA',
    '#2CD31B',
    '#455A29'
];