export const hoursData = [
    { hour: 'Cerrado' },
    { hour: '12 AM' },
    { hour: '12:30 AM' },
    { hour: '1 AM' },
    { hour: '1:30 AM' },
    { hour: '2 AM' },
    { hour: '2:30 AM' },
    { hour: '3 AM' },
    { hour: '3:30 AM' },
    { hour: '4 AM' },
    { hour: '4:30 AM' },
    { hour: '5 AM' },
    { hour: '5:30 AM' },
    { hour: '6 AM' },
    { hour: '6:30 AM' },
    { hour: '7 AM' },
    { hour: '7:30 AM' },
    { hour: '8 AM' },
    { hour: '8:30 AM' },
    { hour: '9 AM' },
    { hour: '9:30 AM' },
    { hour: '10 AM' },
    { hour: '10:30 AM' },
    { hour: '11 AM' },
    { hour: '11:30 AM' },
    { hour: '12 PM' },
    { hour: '12:30 PM' },
    { hour: '1 PM' },
    { hour: '1:30 PM' },
    { hour: '2 PM' },
    { hour: '2:30 PM' },
    { hour: '3 PM' },
    { hour: '3:30 PM' },
    { hour: '4 PM' },
    { hour: '4:30 PM' },
    { hour: '5 PM' },
    { hour: '5:30 PM' },
    { hour: '6 PM' },
    { hour: '6:30 PM' },
    { hour: '7 PM' },
    { hour: '7:30 PM' },
    { hour: '8 PM' },
    { hour: '8:30 PM' },
    { hour: '9 PM' },
    { hour: '9:30 PM' },
    { hour: '10 PM' },
    { hour: '10:30 PM' },
    { hour: '11 PM' },
    { hour: '11:30 PM' }
];

export const categories = [
    { category: 'Parque de diversiones' },
    { category: 'Tienda para bebés' },
    { category: 'Banco' },
    { category: 'Bar' },
    { category: 'Cafetería' },
    { category: 'Carpintería' },
    { category: 'Iglesia' },
    { category: 'Ropa' },
    { category: 'Cocteles' },
    { category: 'Fábrica' },
    { category: 'Ropa femenina' },
    { category: 'Fotografía' },
    { category: 'Jardinería' },
    { category: 'Gasolinera' },
    { category: 'Piñatería' },
    { category: 'Marroquinería' },
    { category: 'Heladería' },
    { category: 'Ferretería' },
    { category: 'Joyería' },
    { category: 'Comida Rápida' },
    { category: 'Librería' },
    { category: 'Financiamiento' },
    { category: 'Logística' },
    { category: 'Centro comercial' },
    { category: 'Mercado' },
    { category: 'Películas' },
    { category: 'Música' },
    { category: 'Odontología' },
    { category: 'Oficina' },
    { category: 'Mascotas' },
    { category: 'Farmacia' },
    { category: 'Pizzería' },
    { category: 'Ropa de alquiler' },
    { category: 'Restaurante' },
    { category: 'Sex shop' },
    { category: 'Zapatería' },
    { category: 'Tecnología' },
    { category: 'Timer' },
    { category: 'Veterinaria' },
    { category: 'Videojuegos' },
    { category: 'Otro' }
];

export const scheduleData = [
    { days: 'Lunes a Viernes' },
    { days: 'Lunes a Domingo' },
    { days: 'Personalizado' }
];

export const headers: string[] = ['Día', 'Abre', 'Cierra'];